const demoData = [
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server Decision Server Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws Decision Server',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server Decision Server Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under:
      'Decision Server Decision Server Decision Server Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws skfdk-vsvdsfs-90ws skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
  {
    ApplicationPublisher: 'IBM',
    ApplicationProduct: 'Decision Server',
    ApplicationName: 'Decision Server',
    ComputerName: 'skfdk-vsvdsfs-90ws',
    Source: 'FMPV',
    Licensable: 'YES',
    Licensable_Under: 'Decision Server',
    Primary_Metric: 'IBM PVU',
    Reviewer: 'Luis Garcia',
    Last_Reviewed: '2020-01-01',
  },
];

const MIColumns = [
  {
    Header: 'Name',
    columns: [
      {
        Header: 'ApplicationPublisher',
        accessor: 'ApplicationPublisher',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'ApplicationProduct',
        accessor: 'ApplicationProduct',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'ApplicationName',
        accessor: 'ApplicationName',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'ComputerName',
        accessor: 'ComputerName',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'Source',
        accessor: 'Source',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'Licensable',
        accessor: 'Licensable',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'Licensable_Under',
        accessor: 'Licensable_Under',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'Primary_Metric',
        accessor: 'Primary_Metric',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'Reviewer',
        accessor: 'Reviewer',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'Last_Reviewed',
        accessor: 'Last_Reviewed',
        // Use a two-stage aggregator here to first
        // count the total rows being aggregated,
        // then sum any of those counts if they are
        // aggregated further
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
      {
        Header: 'edit',
        accessor: 'edit',
        filter: 'none',
        aggregate: 'count',
        Aggregated: ({ value }) => `${value} Names`,
      },
    ],
  },
];

export { demoData, MIColumns };
